spring.application.name=shape-api

# วาง URL ที่ก๊อปมา แล้วปรับตามรูปแบบด้านล่างนี้ครับ
spring.datasource.url=jdbc:postgresql://postgres:db.yuzfsomfeqjdabetlvpo.supabase.co:5432/postgres
spring.datasource.username=postgres
# ใส่รหัสผ่านที่คุณจดไว้ใน Notepad แทนที่ตรงนี้
spring.datasource.password=yBP2nDP1hJwu0QG4

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect